### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by alisa101rs** [jonhoo/ordsearch#20]
Hi! I've been watching your open source maintenance stream, and noticed you've been talking about diving numbers by 256. 
But this code does not do it:

https://github.com/jonhoo/ordsearch/blob/8eb3b2ef21edd187ea920afea17480fc399b243d/benches/search_comparison.rs#L237-L241

I think there are rarely cases when we want to _divide_ and _multiple_ by the same number and there are certainly none for `usize`s (unless the dividend is smaller then 16, but I think in that case it would've been better to express it more explicitly). 
Not sure if that's important or not, just wanted to point that out.

**Comment by jonhoo** [comment]
Ah, I thought we already fixed that, but apparently not in all the cases:

https://github.com/jonhoo/ordsearch/blob/8eb3b2ef21edd187ea920afea17480fc399b243d/benches/search_comparison.rs#L180

In reality this should probably be `% 256` the same way we've done for ^. Would you want to submit a PR?
cc @bazhenov @Qqwy who have been doing a lot of the heavy lifting in this crate recently :muscle:
